[package]
name = "random-color-palette-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hsl = "0.1.1"
image = "0.24.5"
lab = "0.11.0"
rand = "0.8.5"
spinners = "4.1.0"
termion = "2.0.1"
